# -*- coding: utf-8 -*-
"""Salary_predication_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uu1G3fu89M5Kpu7m7GL3XpmA4_0WaMTj
"""

import stremlist as st
import pandas as pd
import joblib

model = joblib.load("salary_prediction_model.pkl")
encoder = joblib.load("label_encoder.pkl")

st.title("Salary Prediction app")

age = st.number_input("Age ", 18,60)
gender = st.selectbox("Gender",encoder["Gender"].classes_)
education = st.selectbox("Education Level",encoder["Education Level"].classes_)
job_title = st.selectbox("Job Title",encoder["Job Title"].classes_)
years_of_experience = st.number_input("Years of Experience",0,20)

df = pd.dataFrame({
    "Age":[age],
    "Gender":[gender],
    "Education Level":[education],
    "Job Title":[job_title],
    "Years of Experience":[years_of_experience]
})


if st.button("Predict"):
  for col in encoder:
    df[col] = encoder[col].transform(df[col])

    predication = model.predict(df)
    st.success(f"predicted salary: {predication[0]:,.2f}")